#
#
#

version: "3.4"

services:
  myjenkins:
    container_name: myjenkins
    build:
      dockerfile: Dockerfile
    # image: jenkins/jenkins:lts
    ports:
      - 8888:8080
      - 126:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - myjenkins:/var/jenkins_home

volumes:
  myjenkins:
